"""Add recruitment fields to project model

Revision ID: 001a10755395
Revises: 293bb114fa17
Create Date: 2025-08-10 06:13:52.745959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001a10755395'
down_revision: Union[str, Sequence[str], None] = '293bb114fa17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_skills', sa.Column('required_proficiency_level', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('recruitment_deadline', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('required_proficiency_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'required_proficiency_level')
    op.drop_column('projects', 'recruitment_deadline')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'estimated_duration')
    op.drop_column('project_skills', 'required_proficiency_level')
    # ### end Alembic commands ###
