"""Add Project, ProjectMember and enhance Client models

Revision ID: 293bb114fa17
Revises: 1b9203dae8a3
Create Date: 2025-08-09 07:05:50.670057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '293bb114fa17'
down_revision: Union[str, Sequence[str], None] = '1b9203dae8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('contribution_level', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_table('project_skills',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('importance_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'skill_id')
    )
    op.add_column('clients', sa.Column('contact_person', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('contact_email', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('notes', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'clients', ['name'])
    op.drop_column('clients', 'contact_info')
    op.add_column('projects', sa.Column('budget', sa.String(length=100), nullable=True))
    op.alter_column('projects', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('projects', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.add_column('skills', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'description')
    op.alter_column('projects', 'end_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('projects', 'start_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('projects', 'budget')
    op.add_column('clients', sa.Column('contact_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'notes')
    op.drop_column('clients', 'website')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'contact_phone')
    op.drop_column('clients', 'contact_email')
    op.drop_column('clients', 'contact_person')
    op.drop_table('project_skills')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_table('project_members')
    # ### end Alembic commands ###
